package com.github.MiguVerse.MiguLoginNext;

import com.google.gson.Gson;
import com.google.gson.reflect.TypeToken;
import io.papermc.paper.plugin.loader.PluginClasspathBuilder;
import io.papermc.paper.plugin.loader.PluginLoader;
import io.papermc.paper.plugin.loader.library.impl.MavenLibraryResolver;
import org.eclipse.aether.artifact.DefaultArtifact;
import org.eclipse.aether.graph.Dependency;
import org.eclipse.aether.repository.RemoteRepository;
import org.jetbrains.annotations.NotNull;

import java.io.BufferedReader;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.lang.reflect.Type;
import java.nio.charset.StandardCharsets;
import java.util.Collections;
import java.util.List;
import java.util.Map;
import java.util.stream.Collectors;

/**
 * Auto-generated by libby-gradle-plugin v1.2.8
 * Do not modify this file manually.
 */
public class GeneratedLibbyLoader implements PluginLoader {
    @Override
    public void classloader(@NotNull PluginClasspathBuilder classpathBuilder) {
        MavenLibraryResolver resolver = new MavenLibraryResolver();

        try (InputStream stream = getClass().getResourceAsStream("/libby.json")) {
            if (stream == null) {
                throw new RuntimeException("libby.json not found in resources");
            }

            String json = new BufferedReader(new InputStreamReader(stream, StandardCharsets.UTF_8))
                    .lines()
                    .collect(Collectors.joining("\n"));

            Gson gson = new Gson();
            Type type = new TypeToken<Map<String, Object>>(){}.getType();
            Map<String, Object> data = gson.fromJson(json, type);

            // Repositories are stored as an array of URL strings
            @SuppressWarnings("unchecked")
            List<String> repositories = data.get("repositories") != null
                    ? (List<String>) data.get("repositories")
                    : Collections.emptyList();

            // Libraries are stored as objects with group, name, version
            @SuppressWarnings("unchecked")
            List<Map<String, Object>> libraries = data.get("libraries") != null
                    ? (List<Map<String, Object>>) data.get("libraries")
                    : Collections.emptyList();

            // Add repositories
            int repoIndex = 0;
            for (String url : repositories) {
                if (url != null && !url.isEmpty()) {
                    String repoId = "libby-repo-" + repoIndex++;
                    resolver.addRepository(new RemoteRepository.Builder(repoId, "default", url).build());
                }
            }

            // Add dependencies
            for (Map<String, Object> lib : libraries) {
                // libby.json uses 'group' and 'name' instead of 'groupId' and 'artifactId'
                String group = (String) lib.get("group");
                String name = (String) lib.get("name");
                String version = (String) lib.get("version");
                String classifier = (String) lib.get("classifier");

                if (group == null || name == null || version == null) {
                    continue; // Skip malformed entries
                }

                // Convert group format: replace {} back to dots
                String groupId = group.replace("{}", ".");

                String coords = groupId + ":" + name + ":" + version;
                if (classifier != null && !classifier.isEmpty()) {
                    coords += ":" + classifier;
                }

                resolver.addDependency(new Dependency(new DefaultArtifact(coords), null));
            }

            classpathBuilder.addLibrary(resolver);
        } catch (Exception e) {
            throw new RuntimeException("Failed to load libby dependencies", e);
        }
    }
}
